# The contents of this config should be *combined* with your existing server configs within Jerbot.
# (I should really write up proper documentation...)
# As always, just don't copy any features you don't want.

# This enables searching of the Binding of Isaac wiki.
wiki: true

# This enables Platinum God- shorthand, more concise versions of the wiki information, but not always as accurate.
platgod: 
  # List of pages from platinumgod.co.uk to scrape
  pages:
  - "original"
  - "rebirth"
  - "antibirth"
  - "afterbirth"
  - "afterbirth-plus"
  - "repentance"
  embed_color: 0xffffff